config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'

  resources :messages do
    collection do
      get :about
      post :search
      get :new_search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include Messenger::Api::Client::Messages

  MAX_MESSAGES = 100

  def index
    @messages = retrieve_all(0, MAX_MESSAGES)
  end

  def create
    destination = params[:destination]
    content = params[:content]

    @send_response = send_message(destination, content)
    if @send_response['success'] == "false"
      flash.now[:error] = @send_response['errors']
      render :new
    else
      flash[:notice] = I18n.t('message_sent')
      redirect_to messages_path
    end
  end

  def about
  end

  def show
    @message = retrieve(params[:id])
  end

  def new_search
  end

  def search
    destination = params[:destination]

    if destination.blank?
      flash.now[:error] = I18n.t('destination_blank')
      render :new_search
    else
      @messages = retrieve_by_destination(destination, nil, MAX_MESSAGES)
      @search = true

      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link?(path_url)
    'active' if current_page?(path_url)
  end

  def prettify_date(date_str)
    return if date_str.blank?

    DateTime.parse(date_str).strftime("%m/%d/%Y (%I:%M:%S %p)")
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def format_transmission_info(transmission)
    return I18n.t('no_data') if transmission.blank?

    transmission['status']
  end
end

app/views/layouts/_navigation.html.erb
<%= image_tag 'PSLogo_7e9e46.png', {class: 'img-fluid', style: 'max-width: 16em'} %>
<ul class="nav nav-tabs mt-2 ml-2">
    <li class="nav-item active">
        <%= link_to I18n.t('links.messages'), messages_path, {class: "nav-link #{active_link?(messages_path)}"} %>
    </li>
    <li class="nav-item">
        <%= link_to I18n.t('links.about'), about_messages_path, {class: "nav-link #{active_link?(about_messages_path)}"} %>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= I18n.t('parent_square') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' unless Rails.env.production? %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('ps.png') %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>
    <div class="p-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="row" onclick="window.location='/messages/<%= msg['id'] %>'">
  <div class="col">
    <%= prettify_date msg['updated_at'] %>
  </div>
  <div class="col text-truncate">
    <%= msg['destination'] %>
  </div>
  <div class="col text-truncate">
    <%= msg['content'] %>
  </div>
  <div class="col">
    <%= msg['transmission']['status'] unless msg['transmission'].blank? %>
  </div>
</div>

app/views/messages/_messages_list.html.erb
<div class="container-fluid mt-2 mb-2">
  <%= render partial: 'messages/list/header' %>

  <% if @messages.empty? %>
    <div class="row m-2 p-2">
      There are currently no messages.
    </div>
  <% end %>

  <!-- Iterate through messages and display -->
  <% @messages.each do |msg| %>
    <%= render partial: 'messages/list/message', locals: { msg: msg } %>
  <% end %>
</div>
<div class="ml-2 mt-3 p-2 weighted rounded text-primary border border-primary">
  >> <%= I18n.t 'max_messages' %>&nbsp;<%= MessagesController::MAX_MESSAGES %>.
</div>

app/views/messages/about.html.erb
<h1>Proposal Introduction</h1>

<div class="p-2 mt-2 mb-2">
  My intent was to showcase my ability to both create a front and back end for a messaging service.  In this case it consists of three parts:
  <ol>
  <li>Front end to display message data, send messages, search messages (based on phone number a.k.a destination)</li>
  <li>Back end to house all the data controls including database and external APIs (i.e. Amazon service)</li>
  <li>Tied with the back end is the unstable nature of the external API that delivery of messages is dependent on</li>
  <li>The idea, overall, was to have a Rails API as the backend serving JSON content to any number of clients using some sort of JS framework (intended as AngularJS). This would be a lightweight way to handle a lot of the frontend processing and allow for a microservice architecture to easily encapsulate functionality and scale across multiple servers.
  </ol>
</div>

<h1>Achievements</h1>
<div class="p-2 mt-2 mb-2">
  I feel I showcased a large portion -- hopefully all -- points made in the original request including flair ideas.  While I'm sure there are some caveats to the way I implemented certain aspects, I know the understanding is that this is with a more concise deadline with looser requirements than would happen in real-world scenarios.  That being said, however, I was very happy with certain aspects that I felt I went above and beyond (or at the very least, above!). Some of these items I'd like to highlight are:

  <ol>
    <li>Used the Rails API mode to create a lightweight rails application -- allowing to use the Rails framework we know and love with a lot less resource overhead.</li>
    <li>In order to increase performance on the UI and offload the asynchronous request to deliver messages, I used sidekiq/redis jobs. These jobs are also slightly more resilient in that they have a retry capacity to a certain degree until the external service was able to deliver the message -- or ultimately failed after the max retry attempt count.</li>
    <li>Extended error handling of error scenarios and alerting the user. I created custom JSON responses with context IDs that would uniquely mark not only the logs with the specific error but also injected an error log into an audit database table. In addition to the context IDs, I also indicated success of most -- if not all -- responses so that the client could handle appropriately. There may be instances in the UI where these responses were not utilitized to the fullest extent but they are where most applicable.</li>
    <li>Able to integrate Bootstrap UI to make a fairly quick and light apperance for the front-end. There are always aspects of Webpacker/bootstrap that seem to egg me on and I did have issues getting bootstrap JS from functioning properly to allow a more interactive experience using items like transitions, modals, etc.</li>
    <li>Was able to integrate a custom messenger-api gem fairly quickly. I was happy that the original classes/modules contained in the gem were in their respective projects -- front & back end -- and were already encapsulated enough so that making this migration was surprisingly simple!</li>
  </ol>
</div>


<h1>Areas of Improvement</h1>
<div class="p-2 mt-2 mb-2">
  In my achievements listing I noted caveats where necessary but a few areas I wanted to expound on -- if I had more time -- are some of the following not mentioned earlier:

  <ol>
    <li>I would have loved to expand the spec coverage -- primarily in the UI and added gem. When I initially began working on the project, I started on the backend and wrote most of my specs accordingly. When I got to the UI I was intending on using Angular vs another rails app but Angular 1 vs current is far different and I wanted to have something to show.</li>
    <li>Better interactive experience using Bootstrap JS or converting to AngularJS. As my proposal mentions, I wanted to have primarily a JS-client with a Rails API back end so that the rails portion could be maximized for performance and scaled quickly/easily.</li>
  </ol>
</div>

app/views/messages/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-3">
      <h2>
        <%= I18n.t 'messages' unless @search %>
        <%= I18n.t 'messages_search_results' if @search %>
      </h2>
    </div>
    <div class="col-9 text-right">
      <%= link_to I18n.t('new_message'), new_message_path, { class: 'btn btn-primary'} %>
      <%= link_to I18n.t('search'), new_search_messages_path, { class: 'btn btn-secondary'} %>
    </div>
  </div>
  <% if flash[:notice] %>
    <div class="row notice p-2 mt-2 mb-2 mr-2 rounded">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <%= render partial: 'messages_list' %>
  </div>
</div>

app/views/messages/list/_header.html.erb
<div class="row bg-dark text-light pt-2">
  <div class="col">
    <h5><%= I18n.t 'messages_list.headers.date_time' %></h5>
  </div>
  <div class="col">
    <h5><%= I18n.t 'messages_list.headers.phone_number' %></h5>
  </div>
  <div class="col">
    <h5><%= I18n.t 'messages_list.headers.message' %></h5>
  </div>
  <div class="col">
    <h5><%= I18n.t 'messages_list.headers.status' %></h5>
  </div>
</div>

app/views/messages/list/_message.html.erb
<div class="row hover" onclick="window.location='/messages/<%= msg['id'] %>'">
  <div class="col">
    <%= prettify_date msg['updated_at'] %>
  </div>
  <div class="col text-truncate">
    <%= msg['destination'] %>
  </div>
  <div class="col text-truncate">
    <%= msg['content'] %>
  </div>
  <div class="col">
    <%= format_transmission_info msg['transmission'] %>
  </div>
</div>

app/views/messages/new.html.erb
<h5 class="ml-2">
  <%= I18n.t('titles.new_message') %>
</h5>

<% if flash[:error] %>
  <div class="row error p-2 m-2 rounded">
    <%= flash[:error] %>
  </div>
<% end %>

<%= form_with url: messages_path do |f| %>
  <div class="p-2">
    <div class="form-group">
      <%= f.label :phone_number, I18n.t('destination') %><br/>
      <%= f.text_field :destination %>
    </div>
    <div class="form-group">
      <%= f.label :message, I18n.t('content') %><br/>
      <%= f.text_area :content, size: '50x5' %>
    </div>
    <br/>
    <%= f.submit I18n.t('send') %>
  </div>
<% end %>

app/views/messages/new_search.html.erb
<h5 class="ml-2">
  <%= I18n.t('titles.search') %>
</h5>

<% if flash[:error] %>
  <div class="row error p-2 m-2 rounded">
    <%= flash[:error] %>
  </div>
<% end %>

<div class="p-2">
  <%= I18n.t('info.search') %>
</div>
<%= form_with url: search_messages_path do |f| %>
  <div class="p-2">
    <div class="form-group">
      <%= f.label :phone_number, I18n.t('destination') %><br/>
      <%= f.text_field :destination %>
    </div>
    <br/>
    <%= f.submit I18n.t('submit') %>
  </div>
<% end %>

app/views/messages/show.html.erb
<div class="p-2">
  <div>
    <h5><%= I18n.t 'messages_list.headers.date_time' %></h5>
    <%= prettify_date @message['updated_at'] %>
  </div>
  <div class="mt-4">
    <h5><%= I18n.t 'messages_list.headers.phone_number' %></h5>
    <%= @message['destination'] %>
  </div>
  <div class="mt-4">
    <h5><%= I18n.t 'messages_list.headers.message' %></h5>
    <%= @message['content'] %>
  </div>
  <div class="mt-4 mb-4">
    <h5><%= I18n.t 'messages_list.headers.status' %></h5>
    <%= format_transmission_info @message['transmission'] %>
  </div>
  <div class="mt-6">
    <%= link_to I18n.t('back'), messages_path, { class: 'btn btn-primary'} %>
  </div>
</div>